services:
  # Auth Service
  - type: web
    name: auth-service
    env: docker
    rootDir: auth-service
    plan: free
    envVars:
      - key: PORT
        value: "8000"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true

  # Core Banking Service
  - type: web
    name: core-banking-service
    env: docker
    rootDir: core-banking-service
    plan: free
    envVars:
      - key: PORT
        value: "8000"
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
